# Generated by Django 2.0.9 on 2024-02-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocatedarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath', models.CharField(max_length=100)),
                ('wardNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('collectedWaste', models.CharField(default=1, max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('complaintDate', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('replyDate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Krishibhavan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pinCode', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('logtitude', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('paymentStatus', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('MATERIALORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.MaterialOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('quantity', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATERIALS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Materials')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ownstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('KRISHIBHAVAN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Krishibhavan')),
                ('MATERIALS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Materials')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('paymentType', models.CharField(max_length=100)),
                ('amount', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('amount', models.CharField(default=1, max_length=100)),
                ('COLLECTIONDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.CollectionDate')),
            ],
        ),
        migrations.CreateModel(
            name='PickupReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('wasteQuantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PickupVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=100)),
                ('vehicleNumber', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('email', models.CharField(default=1, max_length=100)),
                ('fuelType', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Login')),
            ],
        ),
        migrations.CreateModel(
            name='supercoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pinCode', models.CharField(max_length=100)),
                ('wardnumber', models.CharField(default=1, max_length=100)),
                ('houseNumber', models.CharField(default=1, max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetableName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('Amount', models.CharField(default=1, max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableCollectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('Quantity', models.CharField(default=1, max_length=100)),
                ('Price', models.CharField(default=1, max_length=100)),
                ('date', models.CharField(default=1, max_length=100)),
                ('VEGETABLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('paymentStatus', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableOrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('VEGETABLEORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.VegetableOrder')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('Amount', models.CharField(default=1, max_length=10)),
                ('VegetableName', models.CharField(default=1, max_length=10)),
                ('KRISHIBHAVAN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Krishibhavan')),
            ],
        ),
        migrations.CreateModel(
            name='WasteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasteType', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default=1, max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLLECTIONDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.CollectionDate')),
                ('PICKUPVEHICLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.PickupVehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vegetableordersub',
            name='VEGETABLESTOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.VegetableStock'),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='VEGETABLESTOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.VegetableStock'),
        ),
        migrations.AddField(
            model_name='vegetablecart',
            name='VEGETABLESTOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.VegetableStock'),
        ),
        migrations.AddField(
            model_name='pickupreports',
            name='PICKUPVEHICLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.PickupVehicle'),
        ),
        migrations.AddField(
            model_name='pickupreports',
            name='WASTEDETAILS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.WasteDetails'),
        ),
        migrations.AddField(
            model_name='pickuppayment',
            name='PICKUPVEHICLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.PickupVehicle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User'),
        ),
        migrations.AddField(
            model_name='materialscart',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User'),
        ),
        migrations.AddField(
            model_name='materialordersub',
            name='MATERIALS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Materials'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='MATERIALS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Materials'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User'),
        ),
        migrations.AddField(
            model_name='krishibhavan',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Login'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.User'),
        ),
        migrations.AddField(
            model_name='collectiondate',
            name='PICKUPVEHICLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.PickupVehicle'),
        ),
        migrations.AddField(
            model_name='collectiondate',
            name='WASTEDETAILS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.WasteDetails'),
        ),
        migrations.AddField(
            model_name='allocatedarea',
            name='AREA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.Area'),
        ),
        migrations.AddField(
            model_name='allocatedarea',
            name='PICKUPVEHICLE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementSystem.PickupVehicle'),
        ),
    ]
