# Generated by Django 2.0.9 on 2024-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
