# Generated by Django 2.0.9 on 2024-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementSystem', '0002_auto_20240227_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(max_length=1000),
        ),
    ]
